#!/usr/bin/env python3
"""
SSH Key Generator - Educational Security Tool

This tool demonstrates how SSH key pairs work for authentication.
It can generate RSA and Ed25519 key pairs for educational purposes.

EDUCATIONAL PURPOSE ONLY - Learn about SSH key cryptography.
Author: Educational Security Project
"""

import os
import sys
import argparse
import subprocess
import shutil
from pathlib import Path
from typing import Optional, Tuple

# ==============================================================================
# Configuration
# ==============================================================================

# Default key directory
DEFAULT_KEY_DIR = Path.home() / ".ssh"

# Supported key types
KEY_TYPES = {
    "rsa": {
        "bits_default": 4096,
        "bits_min": 2048,
        "algorithm": "rsa",
        "description": "RSA - Most compatible, good for legacy systems"
    },
    "ed25519": {
        "bits_default": 256,
        "bits_min": 256,
        "algorithm": "ed25519",
        "description": "Ed25519 - Modern, fast, secure (RECOMMENDED)"
    },
    "ecdsa": {
        "bits_default": 521,
        "bits_min": 256,
        "algorithm": "ecdsa",
        "description": "ECDSA - Elliptic curve, good balance"
    }
}

# ==============================================================================
# Utility Functions
# ==============================================================================

def ensure_ssh_directory(key_dir: Path) -> bool:
    """
    Ensure the .ssh directory exists with correct permissions.

    Args:
        key_dir: Path to .ssh directory

    Returns:
        True if successful, False otherwise
    """
    try:
        key_dir.mkdir(parents=True, exist_ok=True)

        # Set correct permissions (Unix-like systems)
        if os.name != 'nt':  # Skip on Windows
            os.chmod(key_dir, 0o700)

        return True
    except Exception as e:
        print(f"[!] Error creating directory: {e}")
        return False


def check_openssh_available() -> Tuple[bool, Optional[str]]:
    """
    Check if ssh-keygen is available on the system.

    Returns:
        Tuple of (is_available, path_to_ssh_keygen)
    """
    # Try to find ssh-keygen
    paths_to_try = ["ssh-keygen"]

    # Add common Windows Git paths
    if os.name == 'nt':
        git_paths = [
            "C:\\Program Files\\Git\\usr\\bin\\ssh-keygen.exe",
            "C:\\Program Files (x86)\\Git\\usr\\bin\\ssh-keygen.exe",
        ]
        paths_to_try.extend(git_paths)

    for path in paths_to_try:
        try:
            result = subprocess.run(
                [path, "-V"],
                capture_output=True,
                text=True,
                timeout=5
            )
            # If we get here, ssh-keygen is available
            return True, path
        except FileNotFoundError:
            continue
        except Exception:
            continue

    return False, None


def get_available_keygen() -> Optional[str]:
    """
    Find an available ssh-keygen binary.

    Returns:
        Path to ssh-keygen or None
    """
    # Check if ssh-keygen is in PATH
    path = shutil.which("ssh-keygen")
    if path:
        return path

    # Check Windows Git installation
    if os.name == 'nt':
        git_paths = [
            Path("C:/Program Files/Git/usr/bin/ssh-keygen.exe"),
            Path("C:/Program Files (x86)/Git/usr/bin/ssh-keygen.exe"),
            Path(os.environ.get("ProgramFiles", "") + "/Git/usr/bin/ssh-keygen.exe"),
        ]

        for p in git_paths:
            if p.exists():
                return str(p)

    return None


# ==============================================================================
# Key Generation Functions
# ==============================================================================

def generate_keypair(
    key_type: str,
    key_path: str,
    passphrase: str = "",
    bits: Optional[int] = None,
    comment: str = "",
    email: str = ""
) -> Tuple[bool, str]:
    """
    Generate an SSH key pair using ssh-keygen.

    Args:
        key_type: Type of key (rsa, ed25519, ecdsa)
        key_path: Path where to save the key
        passphrase: Optional passphrase to encrypt the private key
        bits: Key size (not used for ed25519)
        comment: Optional comment for the key
        email: Email address (appended to comment)

    Returns:
        Tuple of (success, message)
    """
    ssh_keygen = get_available_keygen()

    if not ssh_keygen:
        return False, "ssh-keygen not found. Please install OpenSSH or Git."

    # Build comment
    if not comment:
        comment = f"{email}" if email else "Generated by SSH Key Tool"

    # Build command
    cmd = [ssh_keygen, "-t", key_type, "-f", key_path, "-C", comment]

    # Add bits for RSA and ECDSA (not needed for Ed25519)
    if key_type != "ed25519":
        key_info = KEY_TYPES.get(key_type, {})
        key_bits = bits or key_info.get("bits_default", 4096)
        cmd.extend(["-b", str(key_bits)])

    # Add passphrase if provided
    if passphrase:
        cmd.extend(["-N", passphrase])
    else:
        # Empty passphrase (not recommended for production!)
        cmd.extend(["-N", ""])

    try:
        # Run ssh-keygen
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=30
        )

        if result.returncode == 0:
            return True, f"Key pair generated successfully!"
        else:
            error_msg = result.stderr or "Unknown error"
            return False, f"Error generating key: {error_msg}"

    except subprocess.TimeoutExpired:
        return False, "Key generation timed out"
    except Exception as e:
        return False, f"Error: {e}"


def generate_keypair_python(
    key_type: str,
    key_path: str,
    passphrase: str = "",
    bits: int = 4096
) -> Tuple[bool, str]:
    """
    Generate SSH key pair using Python libraries (requires paramiko or cryptography).

    This is an alternative if ssh-keygen is not available.

    Args:
        key_type: Type of key to generate
        key_path: Path to save the key
        passphrase: Passphrase for encryption
        bits: Key size

    Returns:
        Tuple of (success, message)
    """
    try:
        # Try paramiko first
        import paramiko
        from paramiko import Ed25519Key, RSAKey, ECDSAKey

        # Generate key based on type
        if key_type == "ed25519":
            key = Ed25519Key.generate()
        elif key_type == "rsa":
            key = RSAKey.generate(bits=bits)
        elif key_type == "ecdsa":
            key = ECDSAKey.generate()
        else:
            return False, f"Unsupported key type: {key_type}"

        # Write private key
        key.write_private_key_file(key_path, password=passphrase if passphrase else None)

        # Write public key
        public_key_path = f"{key_path}.pub"
        with open(public_key_path, "w") as f:
            f.write(f"{key.get_name()} {key.asbytes().hex()}\n")

        return True, f"Key pair generated using paramiko"

    except ImportError:
        return False, "paramiko not installed. Install with: pip install paramiko"
    except Exception as e:
        return False, f"Error generating key: {e}"


def read_public_key(key_path: str) -> Optional[str]:
    """
    Read the public key from a file.

    Args:
        key_path: Path to private key file

    Returns:
        Public key string or None
    """
    public_key_path = f"{key_path}.pub"

    try:
        with open(public_key_path, "r") as f:
            return f.read().strip()
    except FileNotFoundError:
        return None
    except Exception as e:
        print(f"[!] Error reading public key: {e}")
        return None


def get_key_info(key_path: str) -> dict:
    """
    Get information about an SSH key using ssh-keygen -l.

    Args:
        key_path: Path to private key

    Returns:
        Dictionary with key information
    """
    ssh_keygen = get_available_keygen()

    if not ssh_keygen:
        return {"error": "ssh-keygen not found"}

    try:
        result = subprocess.run(
            [ssh_keygen, "-l", "-f", key_path],
            capture_output=True,
            text=True,
            timeout=10
        )

        if result.returncode == 0:
            # Parse output like: "2048 SHA256:xxxxx... comment (RSA)"
            parts = result.stdout.strip().split()
            if len(parts) >= 4:
                return {
                    "bits": parts[0],
                    "fingerprint": parts[1],
                    "comment": " ".join(parts[3:-1]),
                    "type": parts[-1].strip("()")
                }

        return {"error": result.stderr or "Could not read key info"}

    except Exception as e:
        return {"error": str(e)}


def list_ssh_keys(ssh_dir: Path = DEFAULT_KEY_DIR) -> list:
    """
    List existing SSH keys in the .ssh directory.

    Args:
        ssh_dir: Path to .ssh directory

    Returns:
        List of key file paths
    """
    if not ssh_dir.exists():
        return []

    keys = []
    for f in ssh_dir.glob("*"):
        if f.is_file() and not f.name.endswith(".pub"):
            # Check if corresponding .pub exists
            if (f.parent / f"{f.name}.pub").exists():
                keys.append(str(f))

    return keys


# ==============================================================================
# Output Functions
# ==============================================================================

def print_key_info(key_path: str, public_key: str):
    """Print formatted key information."""
    info = get_key_info(key_path)

    print("\n" + "=" * 60)
    print("                  KEY INFORMATION")
    print("=" * 60)

    if "error" not in info:
        print(f"  Type:        {info.get('type', 'Unknown')}")
        print(f"  Bits:        {info.get('bits', 'Unknown')}")
        print(f"  Fingerprint: {info.get('fingerprint', 'Unknown')}")
        print(f"  Comment:     {info.get('comment', 'None')}")
    else:
        print(f"  Info: {info['error']}")

    print(f"\n  Private Key: {key_path}")
    print(f"  Public Key:  {key_path}.pub")

    print("\n" + "-" * 60)
    print("  PUBLIC KEY (paste this into authorized_keys):")
    print("-" * 60)
    print(f"\n  {public_key}\n")


def print_security_tips():
    """Print educational security tips about SSH keys."""
    tips = """
╔══════════════════════════════════════════════════════════════╗
║                    SSH KEY SECURITY TIPS                     ║
╠══════════════════════════════════════════════════════════════╣
║                                                              ║
║  DO:                                                         ║
║    ✓ Use Ed25519 keys (modern, secure, fast)                ║
║    ✓ Use a strong passphrase for private keys                ║
║    ✓ Protect your private key (chmod 600)                   ║
║    ✓ Backup your keys securely                                ║
║    ✓ Use different keys for different purposes               ║
║    ✓ Rotate keys periodically                                ║
║                                                              ║
║  DON'T:                                                      ║
║    ✗ Share your private key                                  ║
║    ✗ Store private keys in shared locations                  ║
║    ✗ Use keys without passphrases in production             ║
║    ✗ Use the same key across multiple servers               ║
║                                                              ║
║  BEST PRACTICES:                                             ║
║    1. Generate keys locally (not on servers)                ║
║    2. Use ssh-agent to cache passphrase                      ║
║    3. Enable Agent Forwarding carefully                      ║
║    4. Use Certificate Authorities for large deployments     ║
║    5. Monitor key usage with logging                         ║
║                                                              ║
╚══════════════════════════════════════════════════════════════╝
"""
    print(tips)


def print_banner():
    """Display educational banner."""
    banner = """
╔══════════════════════════════════════════════════════════════╗
║           EDUCATIONAL SSH KEY GENERATOR - LEARN             ║
║                                                              ║
║  This tool demonstrates how SSH key pairs work for secure    ║
║  authentication. Learn about public-key cryptography!       ║
║                                                              ║
║  ⚠️  EDUCATIONAL PURPOSE - DO NOT USE FOR ILLEGAL ACTIVITY   ║
╚══════════════════════════════════════════════════════════════╝
"""
    print(banner)


# ==============================================================================
# CLI Interface
# ==============================================================================

def main():
    """Main CLI entry point."""
    parser = argparse.ArgumentParser(
        description="Educational SSH Key Generator",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  %(prog)s -t ed25519 -f mykey              # Generate Ed25519 key
  %(prog)s -t rsa -b 4096 -f server_key     # Generate RSA 4096-bit key
  %(prog)s --list                           # List existing keys
  %(prog)s --info ~/.ssh/id_ed25519         # Show key information

Requirements:
  - OpenSSH installed (comes with Linux/macOS/Git for Windows)
  - Or install paramiko: pip install paramiko
        """
    )

    parser.add_argument(
        "-t", "--type",
        choices=["rsa", "ed25519", "ecdsa"],
        default="ed25519",
        help="Key type (default: ed25519 - RECOMMENDED)"
    )

    parser.add_argument(
        "-b", "--bits",
        type=int,
        help="Key size in bits (for RSA/ECDSA only)"
    )

    parser.add_argument(
        "-f", "--filename",
        help="Output filename (without extension)"
    )

    parser.add_argument(
        "-p", "--passphrase",
        help="Passphrase to encrypt private key"
    )

    parser.add_argument(
        "-c", "--comment",
        help="Comment to add to the key"
    )

    parser.add_argument(
        "-e", "--email",
        help="Email address (added to comment)"
    )

    parser.add_argument(
        "-d", "--directory",
        type=Path,
        default=DEFAULT_KEY_DIR,
        help=f"Output directory (default: {DEFAULT_KEY_DIR})"
    )

    parser.add_argument(
        "--list",
        action="store_true",
        help="List existing SSH keys"
    )

    parser.add_argument(
        "--info",
        metavar="KEY_PATH",
        help="Show information about a key"
    )

    parser.add_argument(
        "-q", "--quiet",
        action="store_true",
        help="Suppress informational output"
    )

    args = parser.parse_args()

    print_banner()

    # List existing keys
    if args.list:
        print("[*] Existing SSH keys:")
        print()

        keys = list_ssh_keys(args.directory)

        if not keys:
            print("  No SSH keys found in ~/.ssh/")
        else:
            for key in keys:
                info = get_key_info(key)
                key_type = info.get('type', 'Unknown')
                bits = info.get('bits', '?')
                print(f"  - {key}")
                print(f"    Type: {key_type}, Bits: {bits}")
                print()

        return 0

    # Show key info
    if args.info:
        info = get_key_info(args.info)
        print(f"[*] Key information for: {args.info}")
        print()

        if "error" in info:
            print(f"  Error: {info['error']}")
        else:
            for key, value in info.items():
                print(f"  {key}: {value}")

        return 0

    # Generate key
    if not args.filename:
        key_type = args.type
        args.filename = f"id_{key_type}"

    key_path = args.directory / args.filename

    # Ensure .ssh directory exists
    if not ensure_ssh_directory(args.directory):
        print("[!] Failed to create SSH directory")
        return 1

    # Check if key already exists
    if key_path.exists():
        response = input(f"[!] Key '{key_path}' already exists. Overwrite? (y/N): ")
        if response.lower() != 'y':
            print("[*] Cancelled.")
            return 0

    print(f"[*] Generating {args.type.upper()} key pair...")

    # Generate key using ssh-keygen
    success, message = generate_keypair(
        key_type=args.type,
        key_path=str(key_path),
        passphrase=args.passphrase or "",
        bits=args.bits,
        comment=args.comment or "",
        email=args.email or ""
    )

    if not success:
        print(f"[!] {message}")

        # Try Python library as fallback
        print("[*] Trying paramiko fallback...")
        success, message = generate_keypair_python(
            key_type=args.type,
            key_path=str(key_path),
            passphrase=args.passphrase or "",
            bits=args.bits or 4096
        )

        if not success:
            print(f"[!] {message}")
            return 1

    print(f"[*] {message}")

    # Read and display public key
    public_key = read_public_key(str(key_path))

    if public_key:
        print_key_info(str(key_path), public_key)
    else:
        print("[!] Warning: Could not read public key")

    # Security tips
    if not args.quiet:
        print_security_tips()

    # Final instructions
    print("\n" + "=" * 60)
    print("                 NEXT STEPS")
    print("=" * 60)
    print(f"""
  1. Your private key is at: {key_path}
     - Keep this SECRET and SECURE
     - Never share it or upload to the internet

  2. Your public key is at: {key_path}.pub
     - This can be shared freely
     - Add to server's ~/.ssh/authorized_keys file

  3. To use your key:
     chmod 600 {key_path}
     ssh -i {key_path} user@server.com

  4. (Optional) Add passphrase to ssh-agent:
     ssh-add {key_path}
""")

    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except KeyboardInterrupt:
        print("\n\n[!] Interrupted by user.")
        sys.exit(130)
    except Exception as e:
        print(f"[!] Error: {e}")
        sys.exit(1)
